Some corrections

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -89,14 +89,16 @@ jobs:
           fi
 
 
-      - name: Upload ISO to GoFile
+
+      - name: Upload image to GoFile
         env:
           GOFILE_TOKEN: ${{ secrets.GOFILE_TOKEN }}
           GOFILE_FOLDER_ID: ${{ secrets.GOFILE_FOLDER_ID }}
         run: |
-          # Path to the ISO file
-#          FILE_PATH="Sirr-OS/SirrOS-pinephonepro-phosh-SirrOS.img"
-    	  cd Sirr-OS
+          cd Sirr-OS
+          device="pinephonepro"
+          environment="phosh"
+          image_file="SirrOS-${device}-${environment}"
           FILE_PATH="${image_file}.img"
 
           if [ ! -f "$FILE_PATH" ]; then
@@ -104,23 +106,32 @@ jobs:
             exit 1
           fi
 
-          # Upload the file
-          RESPONSE=$(curl -s -X POST "https://upload.gofile.io/uploadfile" \
+          echo "📡 Getting server GoFile..."
+          SERVER_JSON=$(curl -s "https://api.gofile.io/servers")
+          SERVER=$(echo "$SERVER_JSON" | jq -r '.data.servers[0].name')
+
+          if [ -z "$SERVER" ] || [ "$SERVER" == "null" ]; then
+            echo "❌ Error getting server: $SERVER_JSON"
+            exit 1
+          fi
+
+          echo "🖥️ Server selected: $SERVER"
+          echo "📤 Uploading file to GoFile..."
+
+          RESPONSE=$(curl -s -X POST "https://${SERVER}.gofile.io/uploadFile" \
             -H "Authorization: Bearer $GOFILE_TOKEN" \
             -F "file=@$FILE_PATH" \
             -F "folderId=$GOFILE_FOLDER_ID")
 
-          # Show full response (for debugging)
-          echo "Full response:"
+          echo "📦 Response completed:"
           echo "$RESPONSE"
 
-          # Extract download link
           LINK=$(echo "$RESPONSE" | jq -r '.data.downloadPage')
           if [ -z "$LINK" ] || [ "$LINK" == "null" ]; then
-            echo "❌ Upload error"
+            echo "❌ Error on a upload"
             exit 1
           fi
 
-          echo "✅ File uploaded successfully! Public link: $LINK"
+          echo "✅ File uploaded correctly!"
+          echo "🔗 Public link: $LINK"
           echo "link=$LINK" >> $GITHUB_OUTPUT
-
